name: flutter_radio_player
description: Flutter radio plugin handles a single streaming media preciously.
version: 1.0.1
author: Sithira Munasinghe <sithiraac@gmail.com>
homepage: http://sithira-munasinghe.me

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.sithiramunasinghe.flutter.flutter_radio_player
    pluginClass: FlutterRadioPlayerPlugin
